### ISSUE TITLE
Validate Dependencies and Scopes when building ServiceProvider

### ISSUE THREAD

**Issue by tobiasbalzano** [BookBeat/knightbus#89]
Currently, when using Microsofts Dependency injection framework, once we build our ServiceProvider we don't validate scopes or dependencies making it harder to catch eventual mistakes when registering dependencies.

This can be handled by passing custom _ServiceProviderOptions_ `new ServiceProviderOptions { ValidateOnBuild = true, ValidateScopes = true }` when using `.UseMicrosoftDependencyInjection` but shouldn't this be the default behaviour?

**Comment by simon-curtis** [comment]
Looks like it's the default behaivour if `ValidateScopes` is not set.

```c#
public static IHostConfiguration UseMicrosoftDependencyInjection(
    this IHostConfiguration configuration, 
    IServiceCollection serviceCollection, 
    ServiceProviderOptions options = null)
{
    configuration.DependencyInjection = new MicrosoftDependencyInjection(serviceCollection, options: options);
    ...
}
```

If the property  `options` is defined and `ValidateScopes` is not set to true it will not be true.

Strangely, inside Microsoft's code, if `options` is null then the value is set to true

```c#
public class MicrosoftDependencyInjection
{
    public MicrosoftDependencyInjection(
        IServiceCollection serviceCollection, 
        IServiceScope scope = null,
        ServiceProviderOptions options = null)
    {
        ...
        _options = options ?? new ServiceProviderOptions {ValidateScopes = true};
    }
}
```

I would suggest creating a custom options class where the the `ServiceProviderOptions` class is always instanced in the `MicrosoftDependencyInjection` constructor

**Comment by NiklasArbin** [comment]
Irrelevant with #90 merged

**Comment by NiklasArbin** [comment]
KnightBus now uses the IHostedServices default way of using DI
